name: Main CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  check-clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: install clang-format
        run: |
          sudo apt-get -y install clang-format
      - name: check clang format
        run: |
          clang-format -i hstream.proto && \
          git diff-index --exit-code HEAD

  # check-buf-lint:
  #   runs-on: ubuntu-latest

  check-haskell-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: haskell/actions/setup@v2
        with:
          ghc-version: "8.10.7"
          cabal-version: "latest"

      - name: install protobuf
        run: |
          sudo apt-get -y install libprotobuf-dev

      - run: |
          git clone --depth 1 https://github.com/hstreamdb/proto3-suite.git
          cd proto3-suite && cabal build all && cabal install compile-proto-file_hstream && cd ..
          PROTO_COMPILE_HS="$HOME/.cabal/bin/compile-proto-file_hstream"
          $PROTO_COMPILE_HS                 \
            --includeDir /usr/local/include \
            --includeDir .                  \
            --proto hstream.proto           \
            --out /dev/null

      - name: Cache Cabal Build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-

  # check-java-build:
  #   runs-on: ubuntu-latest

  check-go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: actions/setup-go@v3
        with:
          go-version: "1.17"

      - name: install protobuf
        run: |
          sudo apt-get -y install protobuf-compiler libprotobuf-dev
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - run: |
          protoc -I . -I /usr/local/include                                  \
                 --go_out=/dev/null      --go_opt=paths=source_relative      \
                 --go-grpc_out=/dev/null --go-grpc_opt=paths=source_relative \
                   ./hstream.proto

  # check-python-build:
  #   runs-on: ubuntu-latest
