name: Main CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  check-clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: install clang-format
        run: |
          apt-get -y install clang-format
      - name: check clang format
        run: |
          clang-format -i hstream.proto && \
          git diff-index --exit-code HEAD

  check-buf-lint:
    runs-on: ubuntu-latest

  check-haskell-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: haskell/actions/setup@v2
        with:
          ghc-version: "8.10.7"
          cabal-version: "latest"

      - run: |
          git clone --depth 1 https://github.com/hstreamdb/proto3-suite.git
          cd proto3-suite && cabal build all && cabal install compile-proto-file_hstream && cd ..
          PROTO_COMPILE_HS="$HOME/.cabal/bin/compile-proto-file_hstream"
          $PROTO_COMPILE_HS                 \
            --includeDir /usr/local/include \
            --includeDir .                  \
            --proto hstream.proto           \
            --out /dev/null

  check-java-build:
    runs-on: ubuntu-latest

  check-go-build:
    runs-on: ubuntu-latest

  check-python-build:
    runs-on: ubuntu-latest
